db:
  image: postgres

uwsgi:
  restart: always
  image: vanessa/{{cookiecutter.project_slug}}
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
  links:
    - redis
    - db

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    #- /etc/ssl/certs:/etc/ssl/certs:ro
    #- /etc/ssl/private:/etc/ssl/private:ro
    #- /var/www/.well-known/acme-challenge/:/var/www/.well-known/acme-challenge/:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:2.8.19
  ports:
    - "6379:6379"

worker:
  image: vanessa/{{cookiecutter.project_slug}}
  command: celery worker -A {{cookiecutter.project_slug}}.celery -Q default -l debug -n default@%h
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
